[mypy] 
ignore_missing_imports = True

[mypy-rclpy] 
ignore_missing_imports = True

[mypy-px4_msgs] 
ignore_missing_imports = True

[mypy-tf_transformations] 
ignore_missing_imports = True

[mypy-ros2_aruco_interfaces]
ignore_missing_imports = True
